"""operations and business

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 08:57:10.958248
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businesses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("public_phone", sa.String(length=100), nullable=True),
        sa.Column("public_email", sa.String(length=320), nullable=True),
        sa.Column("public_contact_name", sa.String(length=200), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("website_score", sa.Integer(), nullable=True),
        sa.Column("opportunity_score", sa.Float(), nullable=True),
        sa.Column("technology_stack", sa.JSON(), nullable=False),
        sa.Column("social_links", sa.JSON(), nullable=False),
        sa.Column("audit", sa.JSON(), nullable=True),
        sa.Column("audited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lead_status", sa.String(length=20), nullable=True),
        sa.Column("outreach_status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_businesses")),
        sa.UniqueConstraint("source", "source_ref", name=op.f("uq_businesses_source")),
    )
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_businesses_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_businesses_city"), ["city"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_type"), ["type"], unique=False)

    op.create_table(
        "experiments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("target", sa.String(length=300), nullable=True),
        sa.Column("expected", sa.Text(), nullable=True),
        sa.Column("budget_inr", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiments")),
    )
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_experiments_status"), ["status"], unique=False)

    op.create_table(
        "knowledge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("agent_slug", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge")),
    )
    with op.batch_alter_table("knowledge", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_knowledge_agent_slug"), ["agent_slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_knowledge_kind"), ["kind"], unique=False)

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price_inr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("billing", sa.String(length=30), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("spec", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_table(
        "tools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("cost_tier", sa.String(length=20), nullable=False),
        sa.Column("permission", sa.String(length=30), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("input_schema", sa.JSON(), nullable=False),
        sa.Column("output_schema", sa.JSON(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tools")),
    )
    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tools_slug"), ["slug"], unique=True)

    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflow_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_workflow"), ["workflow"], unique=False)

    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("company", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_customers_business_id_businesses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("service", sa.String(length=200), nullable=False),
        sa.Column("estimated_value_min_inr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("estimated_value_max_inr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("outreach_draft", sa.Text(), nullable=True),
        sa.Column("next_action", sa.String(length=300), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_leads_business_id_businesses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("business_id", name=op.f("uq_leads_business_id")),
    )
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_leads_status"), ["status"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("workflow_run_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("output_data", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("cost_inr", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], name=op.f("fk_tasks_agent_id_agents")),
        sa.ForeignKeyConstraint(["parent_id"], ["tasks.id"], name=op.f("fk_tasks_parent_id_tasks")),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_tasks_workflow_run_id_workflow_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_agent_id"), ["agent_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tasks_next_attempt_at"), ["next_attempt_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tasks_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tasks_workflow_run_id"), ["workflow_run_id"], unique=False
        )

    op.create_table(
        "approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("agent_slug", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("estimated_cost_inr", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decided_by", sa.String(length=100), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_approvals_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approvals_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvals_task_id"), ["task_id"], unique=False)

    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("amount_inr", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("agent_slug", sa.String(length=100), nullable=True),
        sa.Column("recorded_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_ledger_entries_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_ledger_entries_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ledger_entries_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_ledger_entries_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ledger_entries_occurred_on"), ["occurred_on"], unique=False
        )

    op.create_table(
        "model_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_inr", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_model_usage_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_usage")),
    )
    with op.batch_alter_table("model_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_usage_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_usage_task_id"), ["task_id"], unique=False)

    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("factors", sa.JSON(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("truth", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_opportunities_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
    )
    with op.batch_alter_table("opportunities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_opportunities_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_opportunities_score"), ["score"], unique=False)
        batch_op.create_index(batch_op.f("ix_opportunities_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_opportunities_status"))
        batch_op.drop_index(batch_op.f("ix_opportunities_score"))
        batch_op.drop_index(batch_op.f("ix_opportunities_category"))

    op.drop_table("opportunities")
    with op.batch_alter_table("model_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_usage_task_id"))
        batch_op.drop_index(batch_op.f("ix_model_usage_created_at"))

    op.drop_table("model_usage")
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ledger_entries_occurred_on"))
        batch_op.drop_index(batch_op.f("ix_ledger_entries_kind"))
        batch_op.drop_index(batch_op.f("ix_ledger_entries_category"))

    op.drop_table("ledger_entries")
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_task_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_status"))

    op.drop_table("approvals")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_tasks_parent_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_next_attempt_at"))
        batch_op.drop_index(batch_op.f("ix_tasks_agent_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leads_status"))

    op.drop_table("leads")
    op.drop_table("customers")
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_workflow"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_status"))

    op.drop_table("workflow_runs")
    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tools_slug"))

    op.drop_table("tools")
    op.drop_table("products")
    with op.batch_alter_table("knowledge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_kind"))
        batch_op.drop_index(batch_op.f("ix_knowledge_agent_slug"))

    op.drop_table("knowledge")
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experiments_status"))

    op.drop_table("experiments")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_type"))
        batch_op.drop_index(batch_op.f("ix_events_created_at"))

    op.drop_table("events")
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_businesses_city"))
        batch_op.drop_index(batch_op.f("ix_businesses_category"))

    op.drop_table("businesses")
    # ### end Alembic commands ###
